### ISSUE TITLE
Add IGs charter to charter dashboard

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/charters-dashboard#3]
to make sure they don't fall through the cracks

**Comment by dontcallmedom** [comment]
this is an entirely trivial change from a code perspective; the main question is whether this should be part of the default view of the dashboard, or a separate view. @wseltzer @plehegar  any feedback?

**Comment by wseltzer** [comment]
default, unless PLH prefers otherwise

**Comment by plehegar** [comment]
default is fine.
